#!/bin/sh
# Copyright 2011 Giovanni Totaro
# https://github.com/vannitotaro

NAME=$(basename $0)
HOSTS=/etc/hosts
SECTION_BEGIN="# $NAME BEGIN"
SECTION_END="# $NAME END"

usage() {
    echo "Usage: $0 work|waste"
    exit 1
}

[ $# -ne 1 ] && usage
[ $1 != 'work' -a $1 != 'waste' ] && usage

if [ $(whoami) != 'root' ]; then
    sudo $0 $@
    exit $?
fi

sed -i "/$SECTION_BEGIN/,/$SECTION_END/ d" $HOSTS

echo -n 'Working mode '

if [ $1 = 'work' ]; then
    (
        echo "$SECTION_BEGIN"
        sed -n '/\./ {s/\(.*\)/127.0.0.1 www.\1 \1/g; p}' $(dirname $0)/${NAME}.blacklist
        echo "$SECTION_END"
    ) >>$HOSTS
    echo 'ON :)'
else
    echo 'OFF :('
fi

restart network-manager >/dev/null
